### ISSUE TITLE
Github has released repository "Topics"

### ISSUE THREAD

**Issue by Scrivener07** [Ortham/buddah#22]
Github's new "[Topics](https://github.com/blog/2309-introducing-topics)" allow you to discover networks of similar repositories in a completely new way. This new GitHub feature essentially does what `WrinklyNinja/buddah` already does but with a much broader scope. 

What does this mean for future development on this project? Can these new GitHub features be leveraged to make this project better? Maybe it will make this project obsolete, though time will tell when the networks are more mature. I feel the tighter scope of "game modding" this project offers makes it still relevant and useful. 

Here's to starting a discussion about this in case is was on anyone else's mind as well. 
@WrinklyNinja

**Comment by Ortham** [comment]
Topics seems a neat idea, though I haven't tried them myself. They may obsolete the keywords Buddah has for entries, but they do require repository authors to add them, and they are only for projects hosted on GitHub (which most are, but some aren't).

If GitHub release a Topics API, then Buddah might be able to integrate with it. I guess it's best to just wait and see for now. On the subject of usefulness though, Buddah only gets a few visitors a week, so its usefulness is questionable. 😝

**Comment by Ortham** [comment]
So, after playing around with GitHub Topics, they're pretty neat, but they don't replace Buddah, for the reasons I gave above.
