### ISSUE TITLE
Website "Add A Project" button link is broken.

### ISSUE THREAD

**Issue by Scrivener07** [Ortham/buddah#25]
The "Add A Project" button on the website takes me to a non-existing or unavailable url address.
`https://github.com/WrinklyNinja/buddah/blob/gh-pages/CONTRIBUTING.md`

![capture](https://cloud.githubusercontent.com/assets/1912967/26756646/605628d4-4875-11e7-87de-f780430f384e.PNG)

**Comment by Ortham** [comment]
Thanks, forgot to update that link before I deleted the branch.
