### ISSUE TITLE
Concat selected tag searches.

### ISSUE THREAD

**Issue by Scrivener07** [Ortham/buddah#28]
Whenever a tag is selected it is added to the search field. If another tag is selected the first tag is replaced. Multiple tags can be typed into the search but it would be nice if it worked with clicking the tags too.

What do you think about this idea?

**Comment by Ortham** [comment]
Sorry for the delay, it seems reasonable.

**Comment by Scrivener07** [comment]
Thanks for the reply. I know this is mostly a back-burner project for you. Thanks for the continued support!

**Comment by Scrivener07** [comment]
Awesome, clicking the tags makes it much easier to use. :+1:
